app = "auto-message-scheduler"
primary_region = "ord"

[experimental]
  disable_http_service = true

[build]
  dockerfile = "Dockerfile"

[checks]
  # No health checks, avoids crashing on startup and keeps VM off