app = "auto-message-scheduler"
primary_region = "ord"

[experimental]
  disable_http_service = true

[build]
  dockerfile = "Dockerfile"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  processes = ["cron"]
  
[processes]
  cron = "sleep infinity"