app = "auto-message-scheduler"
primary_region = "ord"

[experimental]
  disable_http_service = true

[build]
  dockerfile = "Dockerfile"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  processes = ["cron"]

[checks]
  # No health checks, avoids crashing on startup and keeps VM off
  
[[cron]]
schedule = "00 00 * * *"
command = "node scheduler.js 00:00"

[[cron]]
schedule = "00 02 * * *"
command = "node scheduler.js 02:00"

[[cron]]
schedule = "00 03 * * *"
command = "node scheduler.js 03:00"

[[cron]]
schedule = "30 03 * * *"
command = "node scheduler.js 03:30"

[[cron]]
schedule = "11 04 * * *"
command = "node scheduler.js 04:11"

[[cron]]
schedule = "00 13 * * *"
command = "node scheduler.js 13:00"

[[cron]]
schedule = "00 14 * * *"
command = "node scheduler.js 14:00"

[[cron]]
schedule = "35 20 * * *"
command = "node scheduler.js 20:35"

[[cron]]
schedule = "45 21 * * *"
command = "node scheduler.js 21:45"

[[cron]]
schedule = "00 22 * * *"
command = "node scheduler.js 22:00"

[[cron]]
schedule = "00 23 * * *"
command = "node scheduler.js 23:00"

[[cron]]
schedule = "45 23 * * *"
command = "node scheduler.js 23:45"
