name: Auto Message Scheduler

on:
  schedule:
    - cron: '00 03 * * *'
    - cron: '00 08 * * *'
    - cron: '00 09 * * *'
    - cron: '00 10 * * *'
    - cron: '30 10 * * *'
    - cron: '30 11 * * *'
    - cron: '00 12 * * *'
    - cron: '30 14 * * *'
    - cron: '00 15 * * *'
    - cron: '35 15 * * *'
    - cron: '45 16 * * *'
    - cron: '00 17 * * *'
    - cron: '00 18 * * *'
    - cron: '30 18 * * *'
    - cron: '35 18 * * *'
    - cron: '45 18 * * *'
    - cron: '00 19 * * *'
    - cron: '00 21 * * *'
    - cron: '00 22 * * *'
    - cron: '30 22 * * *'
    - cron: '35 22 * * *'
    - cron: '40 22 * * *'
    - cron: '11 23 * * *'
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  run-scheduler:
    runs-on: ubuntu-latest
    concurrency:
      group: scheduler
      cancel-in-progress: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci --omit=dev

    - name: Run scheduler
      run: node scheduler.js
