name: Sync Webhooks and Deploy

on:
  workflow_dispatch:  # only manual or API trigger

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download latest webhooks.json
        run: curl -o webhooks.json "https://drive.google.com/file/d/1DpqBHB_-0XxI-ev2-3YT3PONCfFe03Oz/view?usp=sharing"

      - name: Generate fly.toml cron entries
        run: node generate-fly-cron.js

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add webhooks.json fly.toml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update webhooks and cron schedule"
          git push

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest

      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}