name: Update Webhooks and Cron

on:
  workflow_dispatch:

jobs:
  update-webhooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci --omit=dev

    - name: Install gdown
      run: pip install --no-cache-dir gdown

    - name: Download latest webhooks.json from Google Drive
      run: |
        gdown --id 12RANwESLxYGsxT53SbHVK4XmjOcWipYI --no-cookies --output webhooks.json

    - name: Generate cron-times.txt from webhooks
      run: node generate-cron-times.js

    - name: Read cron times into output
      id: cron_times
      run: |
        cron=$(cat .cron-times.txt | tr '\n' ' ')
        echo "cron=$cron" >> $GITHUB_OUTPUT

    - name: Update scheduler.yml schedule
      uses: gr2m/set-cron-schedule-action@v1
      with:
        token: ${{ secrets.GH_PAT }}
        workflow: .github/workflows/scheduler.yml
        cron: ${{ steps.cron_times.outputs.cron }}

    - name: Commit updated webhooks.json and .cron-times.txt
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add webhooks.json .cron-times.txt
        git diff --cached --quiet || git commit -m "Update webhooks.json or .cron-times.txt"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/Jscott-2k/auto-message-scheduler.git
        git push origin main