name: Update Webhooks and Cron

on:
  workflow_dispatch:

jobs:
  update-webhooks:
    runs-on: ubuntu-latest
    concurrency:
      group: update-webhooks
      cancel-in-progress: false
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci --omit=dev

    - name: Install gdown
      run: pip install --no-cache-dir gdown

    - name: Download latest webhooks.json from Google Drive
      run: |
        gdown --id 10NPS386L20ywOvXu7fLPxrU5THrgEMIR --no-cookies --output webhooks.json

    - name: Generate scheduler.yml from webhooks
      run: node generate-scheduler-yml.js

    - name: Commit updated webhooks.json and scheduler.yml
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add webhooks.json .github/workflows/scheduler.yml
        git diff --cached --quiet || git commit -m "Update webhooks.json and scheduler.yml"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/Jscott-2k/auto-message-scheduler.git
        git push origin main 